### ISSUE TITLE
Not working while creating production build

### ISSUE THREAD

**Issue by prgdubey** [rvalenciano/ngx-cron-jobs#18] opened 2018-01-02 14:51 UTC
Hi Team,

We are using the npm module for cron in our project.It works fine in dev. environment.But when we do prod build by executing command npm run build -- prod it shows below warning :- 

_```
vendor.0e0ef8d21e9f6f31317c.bundle.js:1 ERROR Error: No provider for t!
    at x (vendor.0e0ef8d21e9f6f31317c.bundle.js:1)
    at E (vendor.0e0ef8d21e9f6f31317c.bundle.js:1)
    at t._throwOrNull (vendor.0e0ef8d21e9f6f31317c.bundle.js:1)
    at t._getByKeyDefault (vendor.0e0ef8d21e9f6f31317c.bundle.js:1)
    at t._getByKey (vendor.0e0ef8d21e9f6f31317c.bundle.js:1)
    at t.get (vendor.0e0ef8d21e9f6f31317c.bundle.js:1)
    at Be (vendor.0e0ef8d21e9f6f31317c.bundle.js:1)
    at t.get (vendor.0e0ef8d21e9f6f31317c.bundle.js:1)
    at Object.Tn [as resolveDep] (vendor.0e0ef8d21e9f6f31317c.bundle.js:1)
    at t.get (vendor.0e0ef8d21e9f6f31317c.bundle.js:1)
```_
` at Object.updateDirectives (vendor.0e0ef8d21e9f6f31317c.bundle.js:1)
    at Object.updateDirectives (vendor.0e0ef8d21e9f6f31317c.bundle.js:1)
    at cr (vendor.0e0ef8d21e9f6f31317c.bundle.js:1)
    at Cr (vendor.0e0ef8d21e9f6f31317c.bundle.js:1)
    at _r (vendor.0e0ef8d21e9f6f31317c.bundle.js:1)
    at cr (vendor.0e0ef8d21e9f6f31317c.bundle.js:1)
    at Cr (vendor.0e0ef8d21e9f6f31317c.bundle.js:1)
    at _r (vendor.0e0ef8d21e9f6f31317c.bundle.js:1)
    at cr (vendor.0e0ef8d21e9f6f31317c.bundle.js:1)
    at Cr (vendor.0e0ef8d21e9f6f31317c.bundle.js:1)`
Kindly let us know your input on same.

Appreciate for your support.

Regards

**Comment by rvalenciano** [comment] 2018-01-02 15:55
@yp2 any ideas on this one?

**Comment by rvalenciano** [comment] 2018-01-02 16:49
Also @prgdubey can you provide a plunkr or github with a project having the issue?

**Comment by yp2** [comment] 2018-01-02 18:18
Hi @rvalenciano  @prgdubey;

I just build two project in which I use ngx-cron-jobs. All build run smooth with no errors. Also app works as well. One of this build was a demo of ngx-cron-jobs - https://yp2.github.io/ngx-cron-jobs/

I can't reproduce this bug. 

Please provide:
- angular version
- ngx-cron-jobs version
- warning and error with build with source-maps (your logs doesn't provide any information)

**Comment by prgdubey** [comment] 2018-01-03 10:10
Hi @yp2;
These are the dependencies:
`
"dependencies":` {
    "@angular/animations": "^4.2.4",
    "@angular/cdk": "^5.0.3",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/material": "^5.0.3",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "angular2-cron-jobs": "^0.1.0",
    "angular2-infinite-scroll": "^0.3.5",
    "core-js": "^2.4.1",
    "ng2-bootstrap-modal": "^1.0.1",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.4.1",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }`
Here I'm reffering to angular2-cron-jobs not ngx-cron-jobs
[https://www.npmjs.com/package/angular2-cron-jobs]

**Comment by yp2** [comment] 2018-01-03 11:52
@prgdubey 
I don't see angular version. I supposed you use 4.2 but i see some packages with 5.0 so that is very strange.

@rvalenciano This is a question for you why previous version doesn't build. As I remember I had this problem. My solution was to rewrite angular2-cron-jobs.

@prgdubey My solutions for you is to upgrade to ngx-cron-jobs or debug and fix this problem of angular2-cron-jobs. 

@rvalenciano Issue to close.

**Comment by prgdubey** [comment] 2018-01-03 15:00
This is the warning while making the production build - ng build --prod

`WARNING in ./src/$$_gendir/node_modules/angular2-cron-jobs/angular2-cron-jobs.ngfactory.ts
412:106-111 "export 'ɵa' (imported as 'i1') was not found in 'angular2-cron-jobs'
    at HarmonyImportSpecifierDependency._getErrors (D:\project\Bulb Digital\node_modules\webpack\lib\dependencies\HarmonyImpo
rtSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (D:\project\Bulb Digital\node_modules\webpack\lib\dependencies\HarmonyImp
ortSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:694:24)

    at Compilation.finish (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:552:9)
    at applyPluginsParallel.err (D:\project\Bulb Digital\node_modules\webpack\lib\Compiler.js:512:17)
    at D:\project\Bulb Digital\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:498:11)
    at processModuleDependencies.err (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:468:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

WARNING in ./src/$$_gendir/node_modules/angular2-cron-jobs/angular2-cron-jobs.ngfactory.ts
412:138-143 "export 'ɵb' (imported as 'i1') was not found in 'angular2-cron-jobs'
    at HarmonyImportSpecifierDependency._getErrors (D:\project\Bulb Digital\node_modules\webpack\lib\dependencies\HarmonyImpo
rtSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (D:\project\Bulb Digital\node_modules\webpack\lib\dependencies\HarmonyImp
ortSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:694:24)

    at Compilation.finish (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:552:9)
    at applyPluginsParallel.err (D:\project\Bulb Digital\node_modules\webpack\lib\Compiler.js:512:17)
    at D:\project\Bulb Digital\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:498:11)
    at processModuleDependencies.err (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:468:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

WARNING in ./src/$$_gendir/node_modules/angular2-cron-jobs/angular2-cron-jobs.ngfactory.ts
412:145-150 "export 'ɵb' (imported as 'i1') was not found in 'angular2-cron-jobs'
    at HarmonyImportSpecifierDependency._getErrors (D:\project\Bulb Digital\node_modules\webpack\lib\dependencies\HarmonyImpo
rtSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (D:\project\Bulb Digital\node_modules\webpack\lib\dependencies\HarmonyImp
ortSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:694:24)

    at Compilation.finish (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:552:9)
    at applyPluginsParallel.err (D:\project\Bulb Digital\node_modules\webpack\lib\Compiler.js:512:17)
    at D:\project\Bulb Digital\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:498:11)
    at processModuleDependencies.err (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:468:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

WARNING in ./src/$$_gendir/node_modules/angular2-cron-jobs/angular2-cron-jobs.ngfactory.ts
412:99-104 "export 'ɵa' (imported as 'i1') was not found in 'angular2-cron-jobs'
    at HarmonyImportSpecifierDependency._getErrors (D:\project\Bulb Digital\node_modules\webpack\lib\dependencies\HarmonyImpo
rtSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (D:\project\Bulb Digital\node_modules\webpack\lib\dependencies\HarmonyImp
ortSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:694:24)

    at Compilation.finish (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:552:9)
    at applyPluginsParallel.err (D:\project\Bulb Digital\node_modules\webpack\lib\Compiler.js:512:17)
    at D:\project\Bulb Digital\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:498:11)
    at processModuleDependencies.err (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:468:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

WARNING in ./src/$$_gendir/app/dialogmodal/dialogmodal.component.ngfactory.ts
68:28-33 "export 'ɵa' (imported as 'i4') was not found in 'angular2-cron-jobs'
    at HarmonyImportSpecifierDependency._getErrors (D:\project\Bulb Digital\node_modules\webpack\lib\dependencies\HarmonyImpo
rtSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (D:\project\Bulb Digital\node_modules\webpack\lib\dependencies\HarmonyImp
ortSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:694:24)

    at Compilation.finish (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:552:9)
    at applyPluginsParallel.err (D:\project\Bulb Digital\node_modules\webpack\lib\Compiler.js:512:17)
    at D:\project\Bulb Digital\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:498:11)
    at processModuleDependencies.err (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:468:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

WARNING in ./src/$$_gendir/app/dialogmodal/dialogmodal.component.ngfactory.ts
68:35-40 "export 'ɵa' (imported as 'i4') was not found in 'angular2-cron-jobs'
    at HarmonyImportSpecifierDependency._getErrors (D:\project\Bulb Digital\node_modules\webpack\lib\dependencies\HarmonyImpo
rtSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (D:\project\Bulb Digital\node_modules\webpack\lib\dependencies\HarmonyImp
ortSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:694:24)

    at Compilation.finish (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:552:9)
    at applyPluginsParallel.err (D:\project\Bulb Digital\node_modules\webpack\lib\Compiler.js:512:17)
    at D:\project\Bulb Digital\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:498:11)
    at processModuleDependencies.err (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:468:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

WARNING in ./src/$$_gendir/app/dialogmodal/dialogmodal.component.ngfactory.ts
68:67-72 "export 'ɵb' (imported as 'i4') was not found in 'angular2-cron-jobs'
    at HarmonyImportSpecifierDependency._getErrors (D:\project\Bulb Digital\node_modules\webpack\lib\dependencies\HarmonyImpo
rtSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (D:\project\Bulb Digital\node_modules\webpack\lib\dependencies\HarmonyImp
ortSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:694:24)

    at Compilation.finish (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:552:9)
    at applyPluginsParallel.err (D:\project\Bulb Digital\node_modules\webpack\lib\Compiler.js:512:17)
    at D:\project\Bulb Digital\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:498:11)
    at processModuleDependencies.err (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:468:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

WARNING in ./src/$$_gendir/app/dialogmodal/dialogmodal.component.ngfactory.ts
68:74-79 "export 'ɵb' (imported as 'i4') was not found in 'angular2-cron-jobs'
    at HarmonyImportSpecifierDependency._getErrors (D:\project\Bulb Digital\node_modules\webpack\lib\dependencies\HarmonyImpo
rtSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (D:\project\Bulb Digital\node_modules\webpack\lib\dependencies\HarmonyImp
ortSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:694:24)

    at Compilation.finish (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:552:9)
    at applyPluginsParallel.err (D:\project\Bulb Digital\node_modules\webpack\lib\Compiler.js:512:17)
    at D:\project\Bulb Digital\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:498:11)
    at processModuleDependencies.err (D:\project\Bulb Digital\node_modules\webpack\lib\Compilation.js:468:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by yp2** [comment] 2018-01-03 15:10
I suppose than @rvalenciano  will not support this error. 

@prgdubey You have two option - try to debug and fix it or just use ngx-cron-jobs package which works in production builds.

**Comment by rvalenciano** [comment] 2018-01-03 16:07
@prgdubey , I can take a look at the moment of why is not working in < 5 but I have no timeframe for that. Is upgrading to 5 a problem?

**Comment by rvalenciano** [comment] 2018-01-03 16:08
Also, maybe we should close this and @yp2 create a new issue that this is not working with some specific versions of angular?

**Comment by yp2** [comment] 2018-01-03 16:40
@rvalenciano @prgdubey is using **angular2-cron-jobs your old version**. So this issue is **not related to ngx-cron-jobs or specific version of angular**. Your previous version doesn't build with production builds. That was the reason why a rewrite it to new version. Question to you @rvalenciano is that - would you help @prgdubey with your old version - **angular2-cron-jobs**. I can't help in this. **This issue is not related to ngx-cron-jobs.** For me this issue should be closed. @prgdubey should upgrade not version of angular but should change from angular2-cron-jobs to ngx-cron-jobs. New version should work with angular 4.

**Comment by rvalenciano** [comment] 2018-01-03 16:53
Yes, @prgdubey I would encourage to use ngx-cron-jobs, not angular 2 cron jobs, that repo wasn't building because I hadn't finish the build process with a library. @yp2 I was finishing that but you rewrite the library, so I discontinued that project in order to encourage ngx-cron-jobs. I'll close the issue now.

**Closed** 2018-01-03 16:54 UTC
